#!/usr/bin/env bash

set -e

brewNerdFonts='font-hack-nerd-font'
paruNerdFonts='ttf-hack-nerd'
packagesNeeded='neovim ripgrep starship stylua shfmt shellcheck prettier deno antigen'
if [ -x "$(command -v brew)" ] 
then 
  brew install $packagesNeeded $brewNerdFonts
elif [ -x "$(command -v paru)" ]
then 
  paru
  paru -S $packagesNeeded $paruNerdFonts
else 
  echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2
  exit
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
