#!/usr/bin/env bash

set -e

CONFIG_DIR="configs"
CONFIG="${CONFIG_DIR}/install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGINS_DIR="plugins"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

if [ -x "$(command -v brew)" ] 
then 
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/brew.conf.yaml" \
  -p "${PLUGINS_DIR}/dotbot-brew/brew.py"
elif [ -x "$(command -v paru)" ]
then 
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/paru.conf.yaml" \
   -p "${PLUGINS_DIR}/dotbot-paru/paru.py"
elif [ -x "$(command -v apt)" ]
then 
  sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/apt.conf.yaml" \
    -p "${PLUGINS_DIR}/dotbot-apt/apt.py"
fi

if [ $1 = "--rust" ]
then
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/rust.conf.yaml" \
    -p "${PLUGINS_DIR}/dotbot-rust/rust.py"
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"

