Host *
	CanonicalizeHostname yes
	CanonicalDomains jhuapl.edu

host *.jhuapl.edu !gitlab.jhuapl.edu
	ForwardX11 yes
	ForwardX11Trusted yes

host apl-ssh-proxy
	HostName aplssh2.jhuapl.edu
	User freycd1-a

host github.com
	PreferredAuthentications publickey
	IdentityFile ~/.ssh/id_ed25519_personal
	ProxyJump apl-ssh-proxy

Host LL1
	User freycd1
	HostName freycd1-ll1

Host LL3
	User freycd1
	HostName freycd1-ll3
