Host arc-pod
	User freycd1
	HostName arc-cb-ulv1

Host nac201
	User freycd1
	HostName not-a-computer-201

Host nac202
	User user
	HostName not-a-computer-202

Host pod-net-proxy
	User user
	HostName not-a-computer-202

Host pod-563-cpu-a
	User vpx
	HostName 192.168.8.60

Host pod-563-cpu-b
	User vpx
	HostName 192.168.8.61

Host pod-563-nat
	User root
	HostName 192.168.8.69

Host pod-558-cpu-a
	User vpx
	HostName 192.168.8.80

Host pod-558-cpu-b
	User vpx
	HostName 192.168.8.81

Host pod-558-nat
	User root
	HostName 192.168.8.89

Host pod-600-cm
	User engineer
	HostName 192.168.8.101

Host pod-600-cpu-a
	User vpx
	HostName 192.168.8.102

Host pod-600-cpu-b
	User vpx
	HostName 192.168.8.103

Host pod-600-rfc
	User engineer
	HostName 192.168.8.105

Host pod-600-nat
	User root
	HostName 192.168.8.109

Host pod-606-cm
	User engineer
	HostName 192.168.8.121

Host pod-606-cpu-a
	User vpx
	HostName 192.168.8.122

Host pod-606-cpu-b
	User vpx
	HostName 192.168.8.123

Host pod-606-rfc
	User engineer
	HostName 192.168.8.125

Host pod-606-nat
	User root
	HostName 192.168.8.129

Host pod-607-cm
	User engineer
	HostName 192.168.8.161

Host pod-607-cpu-a
	User vpx
	HostName 192.168.8.163

Host pod-607-cpu-b
	User vpx
	HostName 192.168.8.164

Host pod-607-nat
	User root
	HostName 192.168.8.169

Host cobra-cm
	User engineer
	HostName 192.168.14.124

Host cobra-cpu-a
	User vpx
	HostName 192.168.14.125

Host cobra-port-dbfa-a
	User root
	HostName 192.168.14.128

Host cobra-port-dbfa-b
	User root
	HostName 192.168.14.129

Host cobra-port-dbfa-c
	User root
	HostName 192.168.14.130

Host cobra-starboard-dbfa-a
	User root
	HostName 192.168.14.131

Host cobra-starboard-dbfa-b
	User root
	HostName 192.168.14.132

Host cobra-starboard-dbfa-c
	User root
	HostName 192.168.14.133

# POD Net Matching to check if proxying is needed

Match host 192.168.8.* exec "nc -z -w 2 %h 22"
	ProxyJump none

Match host 192.168.8.*
	ProxyJump pod-net-proxy

Match host 192.168.14.* exec "nc -z -w 2 %h 22"
	ProxyJump none

Match host 192.168.14.*
	ProxyJump pod-net-proxy
