Host ARC-RIC
	User freycd1
	HostName arc-rico01
    ForwardX11Trusted yes

Host ENC-SOM
	User analog
	HostName 192.168.2.2

Host RIC2
    User ric
    HostName 192.168.2.2

Host RIC3
    User ric
    HostName 192.168.2.3

Host RIC4
    User ric
    HostName 192.168.2.4
