Host arc-ric
	User freycd1
	HostName arc-rico01

Host enc-som
	User analog
	HostName 192.168.2.2

Host ric2
    User ric
    HostName 192.168.2.2

Host ric3
    User ric
    HostName 192.168.2.3

Host ric4
    User ric
    HostName 192.168.2.4

Match host 192.168.2.* exec "nc -z %h 22"
	ProxyJump none

Match host 192.168.2.*
	ProxyJump ll3
