Host st-net-proxy
	User user
	HostName st-rp1-gw

Host ejc-bench
	User engineer
	HostName 192.168.15.132
	IdentityFile ~/.ssh/kria_super_user_id_ed25519

Host st111
	User engineer
	HostName 192.168.15.134
	IdentityFile ~/.ssh/kria_super_user_id_ed25519

Host lugged-pod
	User engineer
	HostName 192.168.15.136
	IdentityFile ~/.ssh/kria_super_user_id_ed25519
