Host st-net-proxy
	User user
	HostName st-rp1-gw

Host ejc-bench
	User engineer
	HostName 192.168.15.132

Host lugged-pod
	User engineer
	HostName 192.168.15.136

# ST Net Matching to check if proxying is needed

Match host 192.168.15.13* exec "nc -z -w 2 %h 22"
	ProxyJump none

Match host 192.168.15.13*
	ProxyJump st-net-proxy
