# Installs brew if missing
- install-brew: true

# Installs certain brew packages
- brew:
  - git
  - neovim
  - stylua
  - shfmt
  - shellcheck
  - prettier
  - deno 
  - antigen
  - cmake
  - python
  
# Installs certain casks
- cask:
  - font-hack-nerd-font

