- defaults:
    link:
      relink: true

- create:
    - ~/.config
    - ~/.config/zellij

- clean: ['~', '~/.config', '~/.config/zellij']

- link:
    ~/.zshrc: zshrc
    ~/.zshenv: zshenv
    ~/.config/nvim: nvim
    ~/.gitconfig: gitconfig
    ~/.config/starship.toml: starship.toml
    ~/.config/wezterm: wezterm
    ~/.config/zellij/config.kdl: config.kdl

