- cargo:
  - starship
  - eza
  - bob-nvim
  - bat
  - ripgrep
  - git-delta
  - du-dust
  - bottom
  - grex
  - tealdeer
  - fd-find
  - procs
  - sd
  - tokei
  - bandwhich
  - hyperfine
  - zellij
  - cargo-cache
  - cargo-update

