- scoop:
    buckets:
      - extras
      - nerd-fonts
    apps:
      - cmake
      - gcc
      - llvm
      - make
      - modejs
      - neovim
      - python
      - rustup
      - git
      - Hack-NF-Mono
      - Hack-NF

