---
- scoop:
    buckets:
      - main
      - extras
      - nerd-fonts
    apps:
      - cmake
      - gcc
      - llvm
      - make
      - nodejs
      - neovim
      - python
      - rustup
      - git
      - Hack-NF-mono
      - Hack-NF
      - vcxsrv
...
